version: '3.8'

services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    volumes:
      - ghost_content:/var/lib/ghost/content
    environment:
      url: http://localhost:2368

volumes:
  ghost_content:
  mysql_data: